### ISSUE TITLE
Fix current API Version and URL

### ISSUE THREAD

**Issue by dmezquiam** [BaffourAdu/currency-convertor#2]
The current stable API is v7, I also change the url. see https://www.currencyconverterapi.com/docs

**Comment by dmezquiam** [comment]
@BaffourAdu The only repository that I can't upload a new `branch` with some changes (to make a pull request) is this one, do you know why? Do you have something restricted?

**Comment by BaffourAdu** [comment]
@diosbelmezquia there are no restrictions on this repository. Are you trying to push changes to this repository? If so, you will have to push to yours and then open a pull request from your repository to this. I
